stages:
  - build
variables:
  ELASTALERT_VERSION: 0.2.4
  IMAGE_TAG: shuhanghang/$CI_PROJECT_NAME:$CI_COMMIT_TAG

image: docker
services:
  - docker:dind


build:
  stage: build
  only:
    - tags
  tags:
    - gitlab-org-docker
  before_script:
    - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
  script:
    - docker build -t $IMAGE_TAG --build-arg ELASTALERT_VERSION=$ELASTALERT_VERSION .
  after_script:
    - docker images
    - docker push $IMAGE_TAG
    - docker logout
    